export const ActionTypes = {
	FETCH_TODOS_REQUEST: "FETCH_TODOS_REQUEST",
	FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
	FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",

	ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
	ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

	DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
	DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",

	UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
	UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",

	SET_SEARCH_TERM: "SET_SEARCH_TERM",
	SET_SORT_KEY: "SET_SORT_KEY",
};
